### ISSUE TITLE
友链添加请求

### ISSUE THREAD

**Issue by CN-Grace** [zygame1314/XiaoyaDownloader#1]
我之前也有一个小雅的油猴下载脚本，但本人对前端这方面只能说是GPT水平，所以放弃维护了

能不能在readme里放上您项目的地址，方便别人查找捏

**Comment by zygame1314** [comment]
> 我之前也有一个小雅的油猴下载脚本，但本人对前端这方面只能说是GPT水平，所以放弃维护了
> 
> 能不能在readme里放上您项目的地址，方便别人查找捏

当然可以！( •̀ ω •́ )✧

**Comment by CN-Grace** [comment]
> > 我之前也有一个小雅的油猴下载脚本，但本人对前端这方面只能说是GPT水平，所以放弃维护了
> > 能不能在readme里放上您项目的地址，方便别人查找捏
> 
> 当然可以！( •̀ ω •́ )✧

谢谢佬喵
